title: Alicia Jarvis
description: Senior Product Manager, Accessibility Portfolio at Bell / Diversity, Equity & Inclusion Researcher & Strategist / Inclusive Designer
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
