title: Alicia Jarvis
description: Senior Digital Accessibility Specialist at Scotiabank, Diversity, Equity & Inclusion Researcher & Strategist, Inclusive Designer
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate
"colors.background": "#EBDBDB",
gems:
  - jekyll-mentions
