title: Alicia Jarvis
description: Senior Technical Product Manager II at Bell / Product Inclusion Strategist / Designer / Blogger / Speaker
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
